# Generated by Django 5.1.1 on 2024-10-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='tagget_pets',
            new_name='tagged_pets',
        ),
    ]
