# Generated by Django 5.1.1 on 2024-10-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='photo',
            new_name='to_photo',
        ),
    ]
