# Generated by Django 5.1.1 on 2024-10-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_photo_like_to_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='to_photo',
        ),
    ]
